#!/bin/bash
# =============================================================================
# 09_bmfm_gwas_regression_finetuning_sweep.sh
# =============================================================================
# SLURM array job for hyperparameter sweep of BMFM-DNA-SNP GWAS z-score
# regression fine-tuning on the CSD3 SL2 ampere (A100) partition.
#
# Sweep grid (4 array tasks, one per row):
#   Task 0 : max_epochs=2  | loss=mse | lr=1e-6
#   Task 1 : max_epochs=5  | loss=mse | lr=1e-6
#   Task 2 : max_epochs=20 | loss=mse | lr=1e-6
#   Task 3 : max_epochs=50 | loss=mse | lr=1e-6
#
#   Note on Huber loss: BMFM's config does not expose a named 'huber' loss
#   for regression — it would require a custom loss class implementation.
#   Only MSE is included here.
#
# GPU: A100-SXM4 40 GB on CSD3 ampere partition.
#   batch_size=4 + accumulate_grad_batches=16 → effective batch = 64
#   (same effective batch as the dev-gpu-acs run but ~4× faster per epoch)
#
# Checkpointing: Lightning ModelCheckpoint saves the BEST val_loss checkpoint
#   automatically (epoch=N-step=M-val_loss=X.ckpt). Use that for inference,
#   not last.ckpt.
#
# Learning rate: 1e-6 is confirmed to show learning (val MSE ≈ 101 on the
#   by-chrom dataset, R² ≈ 0.91 vs naive baseline). No LR sweep needed yet.
#
# Prerequisites on CSD3:
#   1. conda env 'bmfm' with biomed-multi-omic[dna] installed
#   2. Input data uploaded:
#      scp -r D:/ADNI_SNP_Omni2.5M_20140220/bmfm_inputs/bmfm_gwas_signed_regression_without_ukb_augmented_by_chrom_combos \
#          ec474@login.hpc.cam.ac.uk:~/ADNI_SNP/
#   3. This script and the YAML config pushed to ~/ADNI_SNP/ or cloned from git
#
# Usage:
#   sbatch 09_bmfm_gwas_regression_finetuning_sweep.sh
#   # Monitor:
#   squeue -u ec474
#   # Logs:
#   tail -f logs/bmfm_gwas_sweep_<JOBID>_<TASKID>.out
# =============================================================================

#SBATCH -A COMPUTERLAB-SL2-GPU            # ← adjust to your CSD3 account
#SBATCH --job-name=bmfm_gwas_sweep
#SBATCH --output=logs/bmfm_gwas_sweep_%A_%a.out
#SBATCH --error=logs/bmfm_gwas_sweep_%A_%a.err
#SBATCH --time=12:00:00                   # 12 h covers 50 epochs on A100
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --mem=48G                         # host RAM — FASTA + model + data
#SBATCH --cpus-per-task=8                 # DataLoader workers
#SBATCH --partition=ampere                # A100 40 GB nodes on CSD3
#SBATCH --array=0-3                       # 4 configs (epoch grid)
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=ec474@cam.ac.uk       # ← adjust to your email

# =============================================================================
# ── Sweep parameter grid ──────────────────────────────────────────────────────
# =============================================================================

# Array index → hyperparameters
EPOCH_GRID=(2 5 20 50)

MAX_EPOCHS=${EPOCH_GRID[$SLURM_ARRAY_TASK_ID]}
LOSS_NAME="mse"                          # mse only (huber not supported natively)
LEARNING_RATE="1.0e-6"

# batch_size=4 is safe on A100 40 GB with 8 192 bp sequences + Flash Attention
BATCH_SIZE=4
ACCUM_GRAD=16                            # effective batch = 4 × 16 = 64

# =============================================================================
# ── Paths ─────────────────────────────────────────────────────────────────────
# =============================================================================

CONDA_ENV="bmfm"

# Input: by_chrom_combos forward+reverse split (generated by 08f on local machine)
INPUT_DIRECTORY="${HOME}/ADNI_SNP/bmfm_gwas_signed_regression_without_ukb_augmented_by_chrom_combos/forward_and_reverse"

# Output: separate directory per array task
OUTPUT_DIRECTORY="${HOME}/ADNI_SNP/bmfm_gwas_sweep/mse_lr1e6_epochs${MAX_EPOCHS}"

# Directory containing the YAML config file
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# =============================================================================
# ── Environment ───────────────────────────────────────────────────────────────
# =============================================================================

echo "============================================================"
echo " BMFM-DNA-SNP GWAS Regression — Hyperparameter Sweep"
echo " Array job  : ${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}"
echo " Node       : $SLURMD_NODENAME"
echo " GPU(s)     : $CUDA_VISIBLE_DEVICES"
echo " Epochs     : $MAX_EPOCHS"
echo " Loss       : $LOSS_NAME"
echo " LR         : $LEARNING_RATE"
echo " Batch size : $BATCH_SIZE  (accumulate × $ACCUM_GRAD = effective $(( BATCH_SIZE * ACCUM_GRAD )))"
echo " Input dir  : $INPUT_DIRECTORY"
echo " Output dir : $OUTPUT_DIRECTORY"
echo " Start time : $(date)"
echo "============================================================"

# Activate conda
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate "$CONDA_ENV"

# Verify bmfm is installed
if ! command -v bmfm-targets-run &> /dev/null; then
    echo "[ERROR] bmfm-targets-run not found in conda env '$CONDA_ENV'."
    echo "  Install with: pip install 'biomed-multi-omic[dna]'"
    exit 1
fi

# Validate input directory
if [ ! -d "$INPUT_DIRECTORY" ]; then
    echo "[ERROR] Input directory not found: $INPUT_DIRECTORY"
    echo "  Transfer the dataset with:"
    echo "  scp -r <local_path>/bmfm_gwas_signed_regression_without_ukb_augmented_by_chrom_combos \\"
    echo "      ec474@login.hpc.cam.ac.uk:~/ADNI_SNP/"
    exit 1
fi

mkdir -p "$OUTPUT_DIRECTORY"
mkdir -p logs

# Memory fragmentation hint for long runs
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

# =============================================================================
# ── Fine-tuning run ───────────────────────────────────────────────────────────
# =============================================================================

bmfm-targets-run \
    --config-path "$SCRIPT_DIR" \
    -cn 09_bmfm_gwas_regression_finetuning \
    input_directory="$INPUT_DIRECTORY" \
    working_dir="$OUTPUT_DIRECTORY" \
    "checkpoint='ibm-research/biomed.dna.snp.modernbert.113m.v1'" \
    max_epochs="$MAX_EPOCHS" \
    batch_size="$BATCH_SIZE" \
    accumulate_grad_batches="$ACCUM_GRAD" \
    learning_rate="$LEARNING_RATE"

EXIT_CODE=$?

# ── Save hyperparameters alongside checkpoints ────────────────────────────────
# Written even on failure so partial runs are traceable.
cat > "${OUTPUT_DIRECTORY}/run_config.json" << EOF
{
  "array_task_id":         $SLURM_ARRAY_TASK_ID,
  "job_id":                "${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}",
  "max_epochs":            $MAX_EPOCHS,
  "loss":                  "$LOSS_NAME",
  "learning_rate":         "$LEARNING_RATE",
  "batch_size":            $BATCH_SIZE,
  "accumulate_grad_batches": $ACCUM_GRAD,
  "effective_batch_size":  $(( BATCH_SIZE * ACCUM_GRAD )),
  "input_directory":       "$INPUT_DIRECTORY",
  "output_directory":      "$OUTPUT_DIRECTORY",
  "exit_code":             $EXIT_CODE,
  "finished_at":           "$(date -Iseconds)"
}
EOF

echo "  run_config.json written → ${OUTPUT_DIRECTORY}/run_config.json"

# ── Find best checkpoint for this run ─────────────────────────────────────────
# Lightning names checkpoints: epoch=N-step=M-val_loss=X.ckpt
# Extract the one with the lowest val_loss using sort.
CKPT_DIR="${OUTPUT_DIRECTORY}/lightning_logs"
if [ -d "$CKPT_DIR" ]; then
    BEST_CKPT=$(find "$CKPT_DIR" -name "*val_loss=*.ckpt" ! -name "last.ckpt" \
                | grep -v "last.ckpt" \
                | sort -t= -k4 -g \
                | head -1)
    echo "  Best checkpoint : $BEST_CKPT"
    # Record the best checkpoint path in run_config.json
    python3 -c "
import json, pathlib
path = pathlib.Path('${OUTPUT_DIRECTORY}/run_config.json')
cfg  = json.loads(path.read_text())
cfg['best_checkpoint'] = '${BEST_CKPT}'
path.write_text(json.dumps(cfg, indent=2))
"
fi

echo "============================================================"
echo " Finished at : $(date)"
echo " Exit code   : $EXIT_CODE"
echo "============================================================"

exit $EXIT_CODE
