#!/bin/bash
# =============================================================================
# bmfm_gwas_regression_finetuning.sh
# =============================================================================
# SLURM job script for BMFM-DNA-SNP fine-tuning on signed GWAS z-score
# regression.
#
# Model  : ibm-research/biomed.dna.snp.modernbert.113m.v1  (ModernBERT, 113M)
# Task   : Regression — predict GWAS z-score from allele-specific DNA sequence
# Data   : 430 SNPs × 2 alleles = 860 rows  (688 train / 86 dev / 86 test)
# Input  : bmfm_gwas_signed_regression_without_ukb/ (train/dev/test.csv)
# Config : bmfm_gwas_regression_finetuning.yaml
#
# GPU estimate:
#   ModernBERT 113M @ fp16, 1001 bp sequences, batch=16 → ~4 GB VRAM.
#   Full run (50 epochs, 43 steps/epoch) completes in ~10–20 min on 1× A100.
#   A V100 (32 GB) or A30 (24 GB) are both sufficient; RTX 3090 also works.
#
# Usage:
#   sbatch bmfm_gwas_regression_finetuning.sh
#
# Adjust CONDA_ENV, INPUT_DIRECTORY, OUTPUT_DIRECTORY and SCRIPT_DIR below.
# =============================================================================

#SBATCH --job-name=bmfm_gwas_regression
#SBATCH --output=logs/bmfm_gwas_regression_%j.out
#SBATCH --error=logs/bmfm_gwas_regression_%j.err
#SBATCH --time=02:00:00          # wall time (generous; likely < 30 min)
#SBATCH --gres=gpu:1             # 1 GPU is sufficient
#SBATCH --mem=32G                # host RAM (FASTA + model + dataloaders)
#SBATCH --cpus-per-task=4        # DataLoader workers
#SBATCH --partition=gpu          # adjust to your cluster's GPU partition name

# =============================================================================
# ── User-configurable paths ───────────────────────────────────────────────────
# =============================================================================

CONDA_ENV="bmfm"       # conda env with bmfm_targets installed
                        # install: pip install biomed-multi-omic[dna]

# Directory containing train.csv / dev.csv / test.csv (generated by
# prepare_bmfm_gwas_regression_inputs.py on the local machine, then
# transferred here via scp/rsync):
INPUT_DIRECTORY="/path/to/bmfm_inputs/bmfm_gwas_signed_regression_without_ukb"

# Where to write checkpoints, predictions, logs:
OUTPUT_DIRECTORY="/path/to/output/bmfm_gwas_regression"

# Directory containing bmfm_gwas_regression_finetuning.yaml
# (this repo's snp_pipeline/ folder, cloned from git):
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# =============================================================================
# ── Environment ───────────────────────────────────────────────────────────────
# =============================================================================

echo "============================================================"
echo " BMFM-DNA-SNP GWAS Regression Fine-tuning"
echo " Job ID      : $SLURM_JOB_ID"
echo " Node        : $SLURMD_NODENAME"
echo " GPU(s)      : $CUDA_VISIBLE_DEVICES"
echo " Input dir   : $INPUT_DIRECTORY"
echo " Output dir  : $OUTPUT_DIRECTORY"
echo " Start time  : $(date)"
echo "============================================================"

# Activate conda
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate "$CONDA_ENV"

# Verify bmfm is installed
if ! command -v bmfm-targets-run &> /dev/null; then
    echo "[ERROR] bmfm-targets-run not found in env '$CONDA_ENV'."
    echo "  Install with: pip install 'biomed-multi-omic[dna]'"
    exit 1
fi

mkdir -p "$OUTPUT_DIRECTORY"
mkdir -p logs

# =============================================================================
# ── Fine-tuning run ───────────────────────────────────────────────────────────
# Hydra config: bmfm_gwas_regression_finetuning.yaml (in SCRIPT_DIR)
# This extends dna_finetune_train_and_test_config with:
#   - regression label (z_score, is_regression_label=true)
#   - MSE loss
#   - 1001 bp max_length
# =============================================================================

bmfm-targets-run \
    --config-path "$SCRIPT_DIR" \
    -cn bmfm_gwas_regression_finetuning \
    input_directory="$INPUT_DIRECTORY" \
    output_directory="$OUTPUT_DIRECTORY" \
    checkpoint=ibm-research/biomed.dna.snp.modernbert.113m.v1

EXIT_CODE=$?

echo "============================================================"
echo " Finished: $(date)"
echo " Exit code: $EXIT_CODE"
echo "============================================================"

if [ $EXIT_CODE -ne 0 ]; then
    echo "[ERROR] Fine-tuning failed with exit code $EXIT_CODE"
    exit $EXIT_CODE
fi

echo ""
echo "Outputs written to: $OUTPUT_DIRECTORY"
echo "  predictions.csv   — model predictions on test set"
echo "  checkpoints/      — saved model weights"
echo ""
echo "To run inference on new sequences:"
echo "  bmfm-targets-run -cn dna_predict \\"
echo "      input_directory=\$INPUT_DIRECTORY \\"
echo "      working_dir=\$OUTPUT_DIRECTORY \\"
echo "      checkpoint=\$OUTPUT_DIRECTORY/checkpoints/<best>.ckpt"
