"""
_render_mri_t3_val_macrof1.py
=============================
Regenerate the MRI cross-model T3 VALIDATION LaTeX tables (mri_t3_val.tex + mri_t3_val_filtered.tex)
WITH a true Macro-F1 column per horizon. No tracked generator existed for these .tex files.

Standalone reader (no re-run of 05/06/07 main, no CSV/PNG writes from them): we reuse 07's in-memory
pipeline — collect runs (both layouts) -> backfill augment -> cached-head HP-winner select -> summarise
(06._summarise already computes val_macro_f1_mean/std, the exact macro-F1 reconstructed by 05._val_macro_f1
from the stored val rates) -> relabel cached->parent. Bal.Acc / AUC are preserved verbatim (reformatted to
2 dp) from the existing mri_t3_val.csv; only Macro-F1 is added. '—' where a run logged no val_metrics block.

Out: mri_pipeline/outputs/cross_model/mri_t3_val.tex, mri_t3_val_filtered.tex  (regenerated)
Run: PYTHONIOENCODING=utf-8 python mri_pipeline/_render_mri_t3_val_macrof1.py
"""
import importlib.util
import os
import re
import sys

import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(HERE, "outputs", "cross_model")
T3_TASKS = ["T3a_conv3y", "T3b_conv5y", "T3c_conv7y"]
T3_HDR = ["T3a: conv $\\leq$3y", "T3b: conv $\\leq$5y", "T3c: conv $\\leq$7y"]
MARK = "⁰¹²³⁴⁵⁶⁷⁸⁹†‡"   # superscript / footnote markers to strip from augment labels


def _imp(name, fname):
    spec = importlib.util.spec_from_file_location(name, os.path.join(HERE, fname))
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


def build_summary():
    m07 = _imp("_m07_conv", "07_render_prognostic_conversion_tables.py")
    m06, m06c = m07.m06, m07.m06c
    df = m07._collect_runs_both_layouts(m06.DEFAULT_ROOT)
    df = m06._backfill_augment(df)
    df = m06._filter_cached_to_hp_winners(df)
    summ = m06._summarise(df)
    summ = m07._relabel_cached_to_parent(summ)
    summ["model"] = summ["model"].replace(m06c.MODEL_DISPLAY)
    summ["variant"] = summ["variant"].replace(m06c.VARIANT_DISPLAY)

    def _norm_aug(a):
        base = str(a).rstrip(MARK)                  # strip the † / superscript markers
        return "stochastic" if base == "random" else base   # 06c relabels ViT 'random' -> 'stochastic'
    summ["aug_base"] = summ["augment"].apply(_norm_aug)
    return summ[summ["task"].isin(T3_TASKS)].reset_index(drop=True)


def _aug_base(s):
    return re.sub(f"[{MARK}]", "", str(s))


def _parse_pm(cell):
    """'0.870 ± 0.096' -> (0.870, 0.096); '—' -> (None, None)."""
    m = re.match(r"\s*([\d.]+)\s*±\s*([\d.]+)", str(cell))
    return (float(m.group(1)), float(m.group(2))) if m else (None, None)


def _fmt(mean, std):
    return "--" if mean is None else f"{mean:.2f} \\pm {std:.2f}"


def main():
    summ = build_summary()
    csv = pd.read_csv(os.path.join(OUT_DIR, "mri_t3_val.csv"))

    # rows from the existing CSV (preserve order). cols: Model, "variant / aug", per-horizon Bal.Acc/AUC.
    rows = []
    for _, r in csv.iterrows():
        model = str(r["Model"]).strip()
        variant, aug = [x.strip() for x in str(r["variant / aug"]).split("/")]
        aug_b = _aug_base(aug)
        cells = []   # per horizon: (bacc_m, bacc_s, auc_m, auc_s, mf1_m, mf1_s)
        for hi, (task, hdr_csv) in enumerate(zip(T3_TASKS, ["T3a: conv ≤3y", "T3b: conv ≤5y",
                                                            "T3c: conv ≤7y"])):
            bm, bs = _parse_pm(r[f"{hdr_csv} | Bal.Acc"])
            am, as_ = _parse_pm(r[f"{hdr_csv} | AUC"])
            g = summ[(summ.model == model) & (summ.variant == variant)
                     & (summ.aug_base == aug_b) & (summ.task == task)]
            mm = ms = None
            if not g.empty:
                v = g.iloc[0]["val_macro_f1_mean"]; s = g.iloc[0]["val_macro_f1_std"]
                if pd.notna(v):
                    mm, ms = float(v), (0.0 if pd.isna(s) else float(s))
            cells.append((bm, bs, am, as_, mm, ms))
        rows.append({"model": model, "variant": variant, "aug": aug_b, "cells": cells})

    # diagnostic: which rows got macro-F1
    print("  macro-F1 availability (model / variant / aug : per-horizon mean):")
    for row in rows:
        vals = " ".join("—" if c[4] is None else f"{c[4]:.2f}" for c in row["cells"])
        print(f"    {row['model']:10s} {row['variant']:8s} {row['aug']:14s} : {vals}")

    # bold = best Bal.Acc per (variant, horizon) across all rows
    bold = {}
    for variant in {r["variant"] for r in rows}:
        for hi in range(3):
            best, bi = -1.0, None
            for i, r in enumerate(rows):
                if r["variant"] == variant and r["cells"][hi][0] is not None and r["cells"][hi][0] > best:
                    best, bi = r["cells"][hi][0], i
            bold[(variant, hi)] = bi

    def render(row_idxs, out_path, filtered):
        ncol = 2 + 9
        L = [r"% MRI T3 validation table with Macro-F1 (regenerated by _render_mri_t3_val_macrof1.py)."
             + (" Filtered: best strategy per model." if filtered else ""),
             r"% Macro-F1 = mean of the two per-class F1 (exact, reconstructed from the stored val rates).",
             r"% Requires: \usepackage{booktabs}",
             r"\begin{table}[ht]", r"\centering", r"\small",
             r"\begin{tabular}{ll *{9}{c}}", r"\toprule",
             r" & & \multicolumn{9}{c}{\textbf{T3: binary conversion per window}} \\",
             r"\cmidrule(lr){3-11}",
             " & & " + " & ".join(r"\multicolumn{3}{c}{\textbf{" + h + r"}}" for h in T3_HDR) + r" \\",
             r"\cmidrule(lr){3-5}\cmidrule(lr){6-8}\cmidrule(lr){9-11}",
             r"\textbf{Model} & \textbf{Strategy} & "
             + " & ".join([r"\textbf{Bal.Acc} & \textbf{AUC} & \textbf{Macro-F1}"] * 3) + r" \\",
             r"\midrule"]
        prev_model = None
        for i in row_idxs:
            r = rows[i]
            if not filtered and r["model"] != prev_model:
                if prev_model is not None:
                    L.append(r"\midrule")
                L.append(r"\multicolumn{11}{l}{\textit{" + r["model"] + r"}} \\")
            strat = f"{r['variant']} / {r['aug']}".replace("_", r"\_")
            cells = [r["model"], strat]   # model in col 1 (matches the original; group header repeats it)

            def mc(m, s, boldflag=False):
                if m is None:
                    return "--"
                t = f"{m:.2f} \\pm {s:.2f}"
                return f"$\\mathbf{{{t}}}$" if boldflag else f"${t}$"
            for hi, (bm, bs, am, as_, mm, ms) in enumerate(r["cells"]):
                cells.append(mc(bm, bs, bold.get((r["variant"], hi)) == i))
                cells.append(mc(am, as_))
                cells.append(mc(mm, ms))
            L.append(" & ".join(cells) + r" \\")
            prev_model = r["model"]
        cap = (r"MRI model validation performance for binary AD-conversion at three windows, with "
               r"\textbf{Macro-F1} (mean of the two per-class F1). T3a (conv $\leq$3y: non-conv=35 vs "
               r"converter=4, N=39), T3b (conv $\leq$5y: 23 vs 6, N=29), T3c (conv $\leq$7y: 17 vs 6, "
               r"N=23). Bold = best Bal.Acc per window within each strategy group (full\_ft; frozen). "
               r"Results = mean $\pm$ std across seeds 0/1/2."
               + (" Best strategy per model (highest mean Bal.Acc)." if filtered else ""))
        L += [r"\bottomrule", r"\end{tabular}",
              r"\caption{" + cap + r"}",
              r"\label{tab:mri_t3_val" + ("_filtered" if filtered else "") + r"}", r"\end{table}"]
        with open(out_path, "w", encoding="utf-8") as f:
            f.write("\n".join(L) + "\n")
        print(f"  TEX: {out_path}  ({len(out_path)} ...)")

    render(list(range(len(rows))), os.path.join(OUT_DIR, "mri_t3_val.tex"), filtered=False)
    # filtered: best strategy per model = highest mean Bal.Acc (avg over the 3 windows)
    best_per_model = {}
    for i, r in enumerate(rows):
        score = np.mean([c[0] for c in r["cells"] if c[0] is not None])
        if r["model"] not in best_per_model or score > best_per_model[r["model"]][1]:
            best_per_model[r["model"]] = (i, score)
    filt_idxs = [best_per_model[m][0] for m in ["BrainDINO", "BrainMVP", "ViT-MAE75"]
                 if m in best_per_model]
    render(filt_idxs, os.path.join(OUT_DIR, "mri_t3_val_filtered.tex"), filtered=True)


if __name__ == "__main__":
    main()
